server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
#          uri: git@github.com:renchao05/springcloud-config.git #GitHub上面的git仓库名字
          uri: https://gitee.com/renchao05/springcloud-config.git #GitHub上面的git仓库名字
          skipSslValidation: true
          ####搜索目录
          search-paths:
            - springcloud-config
          default-label:
      #          username: renchao05
#          password: yue@199005
      ####读取分支
      label: main

  #rabbitmq相关配置
  rabbitmq:
    host: 192.168.123.67
    port: 5672
    username: admin
    password: 123

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka


##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'