server:
  port: 84

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: www.mynacos.com:1111
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: 192.168.123.167:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719

# 激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true

#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  user-service: nacos-payment-provider